### ISSUE TITLE
No code, .exe or anything that does as the README.md states.

### ISSUE THREAD

**Issue by ryannair05** [twizzlestorm/task-killer-recoded#1]
Here I am on Github and then I find this program. I see the name and the program looks interesting. I go to the README.md and I see the program is re-configured to C++. That's cool and all, I would have preferred Objective-C++  or, even better, C+- . The sheer disappoint because of the fact that there is no code or program is insurmountable. 

**Please fix this as soon as possible! Thank you**

**Comment by twizzlestorm** [comment]
38

**Comment by twizzlestorm** [comment]
38.2
